project:
  type: website
  resources: images
  output-dir: docs

website:
  navbar: false

format:
  html:
    theme:
      - cosmo
      - brand
    css:
      - style/cil-theme.css
    toc: false
    include-before-body: radar-header.html
    include-after-body: radar-footer.html
    
execute:
  freeze: false